#!/bin/bash
set -e

export CC="gcc"
export CFLAGS="-O2 -flto"
export LDFLAGS="-lm -flto"

rm -rf ./build/
mkdir ./build/
cd ./build/

cmake .. -G "Unix Makefiles" \
	-DCMAKE_BUILD_TYPE=Release \
	-DSDL_TEST_LIBRARY=0 \
	-DSDL_SHARED=0 \
	-DSDL_STATIC=1 \
	\
	-DSDL_AVX=0 \
	-DSDL_AVX2=0 \
	-DSDL_AVX512F=0 \
	\
	-DSDL_MMX=1 \
	-DSDL_SSE=1 \
	-DSDL_SSE2=1 \
	-DSDL_SSE3=1 \
	-DSDL_SSE4_1=1 \
	-DSDL_SSE4_2=1 \
	\
	-DSDL_ALSA=1 \
	-DSDL_PULSEAUDIO=1 \
	-DSDL_DISKAUDIO=0 \
	-DSDL_OSS=0 \
	-DSDL_JACK=0 \
	-DSDL_PIPEWIRE=0 \
	-DSDL_SNDIO=0 \
	\
	-DSDL_OPENGL=1 \
	-DSDL_OPENGLES=0 \
	-DSDL_DIRECTX=0 \
	-DSDL_VULKAN=0 \
	-DSDL_RENDER_VULKAN=0 \
	-DSDL_KMSDRM=0 \
	-DSDL_OFFSCREEN=0 \
	\
	-DSDL_GPU=0 \
	-DSDL_RENDER_GPU=0 \
	-DSDL_CAMERA=0 \
	-DSDL_DUMMYCAMERA=0 \
	-DSDL_JOYSTICK=0 \
	-DSDL_HAPTIC=0 \
	-DSDL_HIDAPI=0 \
	-DSDL_POWER=0 \
	-DSDL_SENSOR=0 \
	-DSDL_DIALOG=0 \
	-DSDL_TRAY=0 \
	-DSDL_VIRTUAL_JOYSTICK=0 \
	\
	-DSDL_X11_XSCRNSAVER=0 \
	-DSDL_X11_XDBE=0 \
	-DSDL_X11_XINPUT=0 \
	-DSDL_X11_XFIXES=0 \
	-DSDL_X11_XTEST=0 \
	\
	-DSDL_WAYLAND=0 \
	\
	-DSDL_RPATH=0 \
	-DSDL_FRIBIDI=0 \
	-DSDL_LIBTHAI=0 \

make clean
